version: "3.9"

services:
  mongo:
    image: mongo:5.0.8
    container_name: mongoDB
    ports:
      - "28018:27017"

  spring:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: spring-boot
    ports:
      - "8080:8080"
    environment:
      - spring.data.mongodb.host=mongo
    depends_on:
      - mongo